#!/usr/bin/env python

import sys
import getopt


def writeRgbColormap(numIntensityLevels, f) :
  f.write('P3\n')
  f.write('%d 1 %d\n' % (numIntensityLevels**3, numIntensityLevels - 1))
  for r in xrange(numIntensityLevels) :
    for g in xrange(numIntensityLevels) :
      for b in xrange(numIntensityLevels) :
        f.write('%d %d %d\n' % (r, g, b))


numIntensityLevels = None
options, args = getopt.getopt(sys.argv[1:], 'n:h')
for opt, par in options :
  if opt == '-h' :
    print 'options:'
    print '-h: print this help and exit'
    print '-n <number of rgb intensity levels>'
    sys.exit()
  elif opt == '-n' :
    numIntensityLevels = int(par)
  else :
    raise StandardError, 'unhandled option "%s"' % opt
if len(args) > 0 :
  outfile = open(args[0], 'w')
else :
  outfile = sys.stdout
writeRgbColormap(numIntensityLevels, outfile)
outfile.close()

