default : rgbcolormaps

rgbcolormaps : makergbcolormap
	./makergbcolormap -n 4 rgb3colormap.ppm
	./makergbcolormap -n 5 rgb4colormap.ppm
	./makergbcolormap -n 6 rgb5colormap.ppm

.PHONY : default rgbcolormaps clean

